// 8-Tailwind/challenge-3/src/Statistics.tsx
import StatisticCard from "./StatisticCard";

export default function Statistics() {
    return (
        <section className="py-20 bg-slate-100">
            <div className="max-w-7xl mx-auto px-8">
                <div className="text-center mb-14">
                    <h2 className=" text-5xl font-black text-slate-900">
                        Global Fleet Statistics
                    </h2>
                    <p className="mt-4 text-lg text-gray-600 max-w-3xl mx-auto">
                        Explore the latest statistics from the world's leading 
                        commercial aircraft manufacturers.
                    </p>
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-8">
                    <StatisticCard
                        title="Aircraft"
                        value={240}
                        color="bg-sky-600"
                    />
                    <StatisticCard
                        title="Airlines"
                        value={85}
                        color="bg-indigo-600"
                    />
                    <StatisticCard
                        title="Countries"
                        value={72}
                        color="bg-purple-600"
                    />
                    <StatisticCard
                        title="Orders"
                        value={1960}
                        color="bg-cyan-600"
                    />
                    <StatisticCard
                        title="Flight Hours"
                        value={245000}
                        color="bg-emerald-600"
                    />
                    <StatisticCard
                        title="Airports"
                        value={680}
                        color="bg-orange-500"
                    />
                    <StatisticCard
                        title="Daily Flights"
                        value={15800}
                        color="bg-pink-600"
                    />
                    <StatisticCard
                        title="Routes"
                        value={920}
                        color="bg-teal-600"
                    />
                </div>
            </div>
        </section>
    );
}

// 8-Tailwind/challenge-2/src/Statistics.vue
<script setup lang="ts">
import StatisticCard from './StatisticCard.vue';
</script>

<template>
    <section class="max-w-7xl mx-auto px-8 py-12">
        <div class="bg-gray-100 rounded-2xl p-8">
            <h2 class="text-3xl font-bold text-center text-gray-800 mb-10">
                Workspace Statistics
            </h2>
            <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
                <div class="hover:scale-105 transition duration-300">
                    <StatisticCard
                        title="AI Tools"
                        :value="12"
                        color="bg-blue-600"
                    />
                </div>
                <div class="hover:scale-105 transition duration-300">
                    <StatisticCard
                        title="Favorites"
                        :value="5"
                        color="bg-green-600"
                    />
                </div>
                <div class="hover:scale-105 transition duration-300">
                    <StatisticCard
                        title="Prompts"
                        :value="128"
                        color="bg-purple-600"
                    />
                </div>
            </div>
        </div>
    </section>
</template>
