// 5-React.js/challenge-7/src/components/EmployeeCard.jsx
import { useState } from "react";
import "../styles/SpeakerCard.css";

function EmployeeCard({ employee }) {

    const [active, setActive] = useState(employee.active);

    function toggleStatus() {
        setActive(!active);
    }

    return (

        <article className="employee-card">

            <div className="employee-avatar">
                {employee.name
                    .split(" ")
                    .map((word) => word[0])
                    .join("")
                }
            </div>

            <h2>{employee.name}</h2>

            <p>
                <strong>Position:</strong>
                {" "}
                {employee.position}
            </p>

            <p>
                <strong>Department:</strong>
                {" "}
                {employee.department}
            </p>

            <p>
                <strong>Years of Service:</strong>
                {" "}
                {employee.yearsOfService}
            </p>

            <p>
                <strong>Salary:</strong>
                {" "}
                $
                {employee.salary.toLocaleString()}
            </p>

            <p
                className={
                    active
                        ? "status active"
                        : "status inactive"
                }
            >
                {
                    active
                        ? "✅ Active"
                        : "❌ Inactive"
                }
            </p>

            <button
                className={
                    active
                        ? "btn-deactivate"
                        : "btn-activate"
                }
                onClick={toggleStatus}
            >
                {
                    active
                        ? "Deactivate Employee"
                        : "Activate Employee"
                }
            </button>

        </article>

    );

}

export default EmployeeCard;

// 06-Vue.js/challenge-2/src/components/EmployeeCard.vue
<script setup>

import "../styles/EmployeeCard.css";

const props = defineProps({
    employee: {
        type: Object,
        required: true
    }
});

function getStatusClass(status) {

    switch (status) {

        case "Active":
            return "active";

        default:
            return "on-leave";

    }

}

const initials = props.employee.name
    .split(" ")
    .map((word) => word[0])
    .join("");

</script>

<template>

    <article class="employee-card">

        <div class="employee-header">

            <div class="avatar">

                {{ initials }}

            </div>

            <div>

                <h2>{{ employee.name }}</h2>

                <p class="position">

                    {{ employee.position }}

                </p>

            </div>

        </div>

        <div class="employee-details">

            <p>

                <strong>Department:</strong>

                {{ employee.department }}

            </p>

            <p>

                <strong>Experience:</strong>

                {{ employee.experience }}
                Years

            </p>

        </div>

        <span
            class="status-badge"
            :class="getStatusClass(employee.status)"
        >

            <template
                v-if="employee.status === 'Active'"
            >

                ✅ {{ employee.status }}

            </template>

            <template
                v-else
            >

                🟡 {{ employee.status }}

            </template>

        </span>

    </article>

</template>
