// 05-React.js/challenge-8/src/components/ProductCard.jsx
import { useState } from "react";
import "../styles/ProductCard.css";

function ProductCard({ product }) {

    const [available, setAvailable] = useState(
        product.available
    );

    function toggleAvailability() {

        setAvailable(!available);

    }

    return (

        <article className="product-card">

            <div className="card-header">

                <h2>{product.name}</h2>

                {
                    product.featured && (
                        <span className="featured-badge">
                            ⭐ Featured
                        </span>
                    )
                }

            </div>

            <div className="card-content">

                <p>
                    <strong>Brand:</strong>
                    {" "}
                    {product.brand}
                </p>

                <p>
                    <strong>Category:</strong>
                    {" "}
                    {product.category}
                </p>

                <p>
                    <strong>Price:</strong>
                    {" "}
                    $
                    {product.price.toLocaleString(
                        undefined,
                        {
                            minimumFractionDigits: 2,
                            maximumFractionDigits: 2
                        }
                    )}
                </p>

                <p>
                    <strong>Stock:</strong>
                    {" "}
                    {product.stock} Units
                </p>

                {
                    product.stock < 10 && (
                        <p className="low-stock">
                            ⚠️ Low Stock
                        </p>
                    )
                }

                <p
                    className={
                        available
                            ? "status available"
                            : "status unavailable"
                    }
                >
                    {
                        available
                            ? "✅ Available"
                            : "❌ Unavailable"
                    }
                </p>

            </div>

            <button
                className={
                    available
                        ? "btn-disable"
                        : "btn-enable"
                }
                onClick={toggleAvailability}
            >
                {
                    available
                        ? "Disable Product"
                        : "Enable Product"
                }
            </button>

        </article>

    );

}

export default ProductCard;

// 6-Vue.js/challenge-3/src/components/ProductCard.vue
<script setup>

import "../styles/ProductCard.css";

const props = defineProps({
    product: {
        type: Object,
        required: true
    }
});

function getStockClass(stock) {

    if (stock > 30) {

        return "in-stock";

    }

    if (stock >= 10) {

        return "limited-stock";

    }

    return "low-stock";

}

function getStockLabel(stock) {

    if (stock > 30) {

        return "🟢 In Stock";

    }

    if (stock >= 10) {

        return "🟡 Limited Stock";

    }

    return "🔴 Low Stock";

}

</script>

<template>

    <article class="product-card">

        <header class="card-header">

            <div>

                <h2>

                    {{ product.name }}

                </h2>

                <p class="category">

                    {{ product.category }}

                </p>

            </div>

            <span
                v-if="product.featured"
                class="featured-badge"
            >

                ⭐ Featured

            </span>

        </header>

        <section class="product-details">

            <p>

                <strong>Supplier:</strong>

                {{ product.supplier }}

            </p>

            <p>

                <strong>Price:</strong>

                ${{ product.price.toFixed(2) }}

            </p>

            <p>

                <strong>Stock:</strong>

                {{ product.stock }} Units

            </p>

        </section>

        <footer class="card-footer">

            <span
                class="stock-badge"
                :class="
                    getStockClass(product.stock)
                "
            >

                {{ getStockLabel(product.stock) }}

            </span>

        </footer>

    </article>

</template>
